global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
    # monitor: 'codelab-monitor'

#rule_files:
#  - 'prometheus.rules'

scrape_configs:
  - job_name: 'USA'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['MACHINE_2:18080', 'MACHINE_4:18080']

  - job_name: 'EU'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['MACHINE_1:18080', 'MACHINE_3:18080']

  # Click metrics
  - job_name: 'Click_metrics'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['CLICK_METRICS:9090']