global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

#rule_files:
#  - 'prometheus.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus_name'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['146.185.143.81:19090']
        labels:
          group: 'prometheus_group'
      

  - job_name: 'USA'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['198.199.120.228:18080', '198.199.120.228:18080']
      
  - job_name: 'EU'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 5s
    # scrape_timeout: 10s
    static_configs:
      - targets: ['146.185.143.81:18080', '146.185.153.64:18080', '146.185.143.81:18080']
      
# Cost metrics
  - job_name: 'Cost_metrics'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 1m
    # scrape_timeout: 10s
    static_configs:
      - targets: ['54.246.169.99:80']
      
# Click metrics
  - job_name: 'Click_metrics'
    # Override the global default and scrape targets from this job every second.
    scrape_interval: 1m
    # scrape_timeout: 10s
    static_configs:
      - targets: ['146.185.143.81:9090']
